name: Shell Lint

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
     - name: Check out code
       uses: actions/checkout@v4

     - name: Run ShellCheck
       uses: ludeeus/action-shellcheck@master
       with:
        files: |
            disk_usage_report.sh
            disk_alert.sh
